### ISSUE TITLE
Investigate why SQL database costs are so high

### ISSUE THREAD

**Issue by dthaler** [orcasound/orcanode-monitor#85]
Instead of an Azure SQL database that is $10/day to keep IFTTT running, what happens if we try a local database?

- [x] Remove environment variable from staging service
- [x] See whether a local SQL database will work on Azure (answer: no)
- [x] Investigate whether closing the database connection is sufficient.
- If not, investigate just using a .csv or .json or .xml log file store for log storage.  See https://github.com/morrisjdev/FileContextCore
- Also if not, investigate backing up to Azure SQL database at a low frequency
- [x] Test staging service
- [x] Roll out to production if it passes testing

```[tasklist]
### Tasks
```

**Comment by dthaler** [comment]
Learning: using a Local DB on Azure doesn't work:
```
SqlException: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 52 - Unable to locate a Local Database Runtime installation. Verify that SQL Server Express is properly installed and that the Local Database Runtime feature is enabled.)
```

**Comment by dthaler** [comment]
Learning: adding "Pooling=False" to the connection string appears to solve the issue locally, as determined from SQL Server Profiler.  Without it, the connection pooling feature seems to keep the connection up for a long time.
